version: "3.9"

services:
  db:
    image: postgres:15
    container_name: krypto-db
    restart: always
    environment:
      POSTGRES_DB: krypto
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
